### ISSUE TITLE
GitHub doesn't seem to recognize the tags as releases; Zenodo version is 2.0

### ISSUE THREAD

**Issue by DWesl** [mcuntz/hesseflux#1]
The most recent [release GitHub knows about](https://github.com/mcuntz/hesseflux/releases) is 2.0, which matches [the version archived at Zenodo](https://zenodo.org/record/3831489).  There have been [seven tags](https://github.com/mcuntz/hesseflux/tags) since then, [many of which are available on PyPI](https://pypi.org/project/hesseflux/).  

Could you tell GitHub that the most recent tag should also count as a release?  Uploading it to Zenodo would simplify citing the package a bit, but I can work without that.

**Comment by mcuntz** [comment]
Hey @DWesl ,

yes, it seems like that you have to make a release on Github to trigger a Zenodo release. I normally just tag with git on the command line.

I had planned to change to the pyproject.toml structure and use my updated pyjams package in hesseflux before adding a release to Zenodo. But I can just create a release from the current state of the repo next week. No worries. I will ping you when it is done.

Kind regards,
Matthias

**Comment by mcuntz** [comment]
Hey @DWesl ,

I have just published a release version on Zenodo (v.3.2.1).

Thanks for any feedback,
Matthias

**Comment by DWesl** [comment]
Thank you; I just got the Bibtex file from Zenodo and into the paper.
