### ISSUE TITLE
link to User Guide is broken

### ISSUE THREAD

**Issue by yagciali2002** [mcuntz/hesseflux#2]
Hi,

The link to User Guide (See the [User Guide](https://mcuntz.github.io/pyjams/html/userguide.html) for a step by step guide through the script and the configuration file.) on https://github.com/mcuntz/hesseflux is not working. I am getting the message below. The llink needs to be updated

Best

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

**Comment by mcuntz** [comment]
@yagciali2002 Thanks.
Small typo. Fixed now.
Kind regards,
Matthias
